### ISSUE TITLE
Still development?

### ISSUE THREAD

**Issue by PixelT** [mskv/sublime-sidebar-on-hover#1]
Hi,

Is this project still development?
Did you have plan to submit it on packagecontrol ?
If yes, when? :)

**Comment by mskv** [comment]
@PixelT Hi! Sorry for not responding, I had my notifications turned off for some reason.

The plugin is usable - I use it every day rarely having any issues. It is supported in a sense that I will try to fix any breaking issues that may arise. Plus there were some changes to the Sublime Text's Python API that will let me get rid of some of the logic and make the code cleaner, so I'll get to it when I have time. But I don't plan to port it to Windows and Linux unfortunately.

As to the packagecontrol - I don't think I can do that. The plugin requires a mouse-tracking binary to work and I don't think I can ship an arbitrary binary with my package. So instead I provided an instruction how to compile the ObjC code provided with the repo.

To be honest I didn't expect ANY interest in this project, thanks :)
